upstream banana_forest {
	server dataserver1.banana.local:30000;
	server dataserver2.banana.local:30000;

	#server 192.168.80.51 weight=2;
	#server 192.168.80.52 weight=1;
}

server{
	listen 443 ssl default_server;
	server_name banana.local www.banana.local 192.168.30.31;
	#root /var/www/port81;
	server_tokens off;
	proxy_hide_header Server;
	ssl_certificate /etc/nginx/banana.crt;
	ssl_certificate_key /etc/nginx/banana.key;

	ssl_protocols TLSv1.2 TLSv1.3;
	ssl_ciphers HIGH:!aNULL:!MD5;

	proxy_intercept_errors on;
	error_page 502 503 504 /index.html;

	location / {
		proxy_pass http://banana_forest;

		proxy_hide_header X-Powered-By;
		proxy_hide_header Server;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		proxy_next_upstream error timeout http_502;

	}

	location = /index.html{
		root /var/www/port443;

	}

}
